title: Deep Intelligence Documentation
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - API-OAUTH.md
  - API.md
  - DASHBOARDS.md
  - EXTERNAL-SOURCES.md
  - IFRAME-TOKENS.md
  - SOURCES.md
  - CUSTOM-VIEW.md
